export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const LOAD_ADVERTS_FAILURE = 'LOAD_ADVERTS_FAILURE';

// export const TAGS_LOADED_REQUEST = 'TAGS_LOADED_SUCCESS';
export const TAGS_LOADED_SUCCESS = 'TAGS_LOADED_SUCCESS';
export const LOAD_TAGS_FAILURE = 'LOAD_TAGS_FAILURE';

// export const ADVERT_LOADED_REQUEST = 'ADVERT_LOADED_REQUEST';
export const ADVERT_LOADED_SUCCESS = 'ADVERT_LOADED_SUCCESS';
export const LOAD_ADVERT_FAILURE = 'LOAD_ADVERT_FAILURE';

export const DELETE_ADVERT_REQUEST = 'DELETE_ADVERT_REQUEST'
export const DELETE_ADVERT_SUCCESS = 'DELETE_ADVERT_SUCCESS';
export const DELETE_ADVERT_FAILURE = 'DELETE_ADVERT_FAILURE';

// newAdvertPage
export const ADVERT_CREATED_SUCCESS = 'ADVERT_CREATED_SUCCESS';
export const ADVERT_CREATED_FAILURE = 'ADVERT_CREATED_FAILURE';

export const UI_RESET_ERROR = 'UI_RESET_ERROR';
